version: '3.4'

services:
  catelogdb:
    container_name: catelogdb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
       
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
      
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/   
      
  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=hasty.maloos70@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=hasty1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
   

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000" 
      - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data

  catalogapi:
    container_name: catelogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DataBaseSettings:ConnectionString=mongodb://catelogdb:27017"
    depends_on:
      - catelogdb
    ports:
      - "8000:80"
  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:connectionstring=basketdb:6379"
    depends_on:
      - basketdb
    ports:
      - "8001:80"


  discountapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

