version: '3.4'

services:
  catelogdb:
    container_name: catelogdb
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - mongo_data:/data/db
       
  basketdb:
    container_name: basketdb
    restart: always
    ports:
      - "6379:6379"
      
  discountdb:
    container_name: discountdb
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=DiscountDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/ 
      
  orderdb:
    container_name: orderdb
    environment:
       SA_PASSWORD: "hastifallah"
       ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=hasty.maloos70@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=hasty1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
   

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000" 
      - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data

  catalogapi:
    container_name: catelogapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DataBaseSettings:ConnectionString=mongodb://catelogdb:27017"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - catelogdb
    ports:
      - "8000:80"

  basketapi:
    container_name: basketapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:connectionstring=basketdb:6379"
      - "GRPCSettings:DiscountURL=http://discountgrpc"
      - "EventBusSetting:HostService=amqp://guest:guest@rabbitmq:5672"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:80"


  discountapi:
    container_name: discountapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseConnection:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - discountdb
    ports:
      - "8002:80"


  discountgrpc:
    container_name: discountgrpc 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseConnection:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - discountdb
    ports:
      - "8003:80"


  orderingapi:
    container_name: orderingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;password=hastifallah;"
      - "EventBusSetting:HostService=amqp://guest:guest@rabbitmq:5672"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - orderdb
      - rabbitmq
    ports:
      - "8004:80"


  ocelotapigw:
    container_name: ocelotapigw
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
       - catalogapi
       - basketapi
       - discountapi
       - orderingapi
    ports:
      - "8010:80"

  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:CatalogUrl=http://catalogapi"
      - "ApiSettings:BasketUrl=http://basketapi"
      - "ApiSettings:OrderingUrl=http://orderingapi"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - catalogapi
      - basketapi
      - orderingapi
    ports:
      - "8005:80"

  aspnetrunbasics:
    container_name: aspnetrunbasics
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GateWayAddress=http://ocelotapigw"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - ocelotapigw
      - catalogapi
      - basketapi
      - orderingapi
      - discountapi
    ports:
      - "8006:80"

  elasticsearch:
    container_name: elasticsearch
    environment:
        - xpack.monitoring.enabled=true
        - xpack.watcher.enabled=false
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - discovery.type=single-node
    ports:
        - "9200:9200"
    volumes:
        - elastiksearch_data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    environment:
        - ELASTICSEARCH_URL=http://elasticsearch
    depends_on:
        - elasticsearch
    ports:
        - "5601:5601"

  blazorapp1:
    container_name: blazorapp1
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ApiSettings:GatewayAddress=http://ocelotapigw"
      - "ElastikSearchConfiguration:Uri=http://elasticsearch"
    depends_on:
      - ocelotapigw
      - catalogapi
      - basketapi
      - orderingapi
      - discountapi
    ports:
      - "8007:80"


  identityserver:
    container_name: identityserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:IdentityServerConnectionString=Server=identityserverdb;Port=3306;Database=IdentityServerDb;User Id=root;Password=Abcd1234;"
      - "ElasticConfiguration:Uri=http://elasticsearch:9200"
    depends_on:
    - identityserverdb
    ports:
      - "8015:80"

